import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import { loadPosts } from '../lib/loadPosts'

const Home = () => {
  return (
    <Layout >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <h1>Welcome to the layout component...</h1>
         <h2>TIMESTAMP:{Date.now()}</h2>

    </Layout>
  )
}

export default Home

