import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import { loadPosts } from '../lib/loadPosts'

const Home = () => {
  return (
    <Layout >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <h2>Welcome to the post crud app...</h2>
         

    </Layout>
  )
}

export default Home

